# Generated by Django 4.2.3 on 2023-07-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0003_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(default='leeg', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='portions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
