# Generated by Django 4.2.3 on 2023-07-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0004_recipe_category_recipe_portions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingredientPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost.ingredient')),
            ],
        ),
    ]
