# Generated by Django 4.2.3 on 2023-07-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0005_ingredientprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='price',
        ),
    ]
